packages:
  - "packages/*"
  - "packages/@vitecut/timeline"
  - "packages/@vitecut/canvas"
  - "packages/@vitecut/utils"
  - "packages/@vitecut/history"
  - "packages/@vitecut/media"
  - "packages/@vitecut/project"
  - "packages/@vitecut/audio"
  - "packages/@vitecut/renderer"
  - "packages/@vitecut/record"
