packages:
  - "packages/*"
  - "packages/@vitecut/canvas"
  - "packages/@vitecut/utils"
  - "packages/@vitecut/history"
  - "packages/@vitecut/media"
  - "packages/@vitecut/project"
  - "packages/@vitecut/storage"
  - "packages/@vitecut/audio"
  - "packages/@vitecut/record"
  - "packages/@vitecut/hotkeys"
  - "packages/@vitecut/workflow"
