name: Build Base Image

on:
  push:
    paths:
      - "Dockerfile.base"
      - "package.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 登录 Gitea 内部仓库
      - name: Log in to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: 47.110.148.112:8081
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.MY_GITEA_TOKEN }}

      # 2. 提取元数据 (自动处理小写)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # 注意：镜像路径包含 IP 和 端口
          images: 47.110.148.112:8081/${{ gitea.repository_owner }}/vitecut-base
          tags: |
            type=raw,value=latest
            type=sha,format=short

      # 3. 设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # 针对非 HTTPS 仓库的特殊驱动配置
          driver-opts: |
            image=moby/buildkit:master
            network=host

      # 4. 构建并推送
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 放弃 GitHub 专用的 gha 缓存，改用 inline
          cache-from: type=inline
          cache-to: type=inline,mode=max
