steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Log in to GHCR
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # 自动提取元数据并处理大小写
  - name: Extract Docker metadata
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: ghcr.io/${{ github.repository_owner }}/vitecut-base
      tags: |
        type=raw,value=latest

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      context: .
      file: ./Dockerfile.base
      push: true
      # 直接引用 meta 步骤生成的 tags
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
